### ISSUE TITLE
FFmpeg not working with kde runtime 5.12

### ISSUE THREAD

**Issue by Bleuzen** [flathub/com.github.Bleuzen.FFaudioConverter#1]
FFmpeg doesn't build properly with kde runtime version 5.12.

With kde runtime 5.12 it builds and uploads to flathub, but the built version doesn't work. FFmpeg in this sandbox prints:
```
WARNING: library configuration mismatch
```
when starting.

The built FFmpeg version is useless, because it always prints this warning and
```
Unable to find a suitable output format for ...
```
for every format I tried. This is not normal. It works when using kde platform 5.11.

I also did a local build with the kde runtime / sdk 5.12 on my Manjaro machine with flatpak 1.1.2. It works there. The problem seems to be with the flathub build server.

**Comment by Bleuzen** [comment]
@TingPing @barthalion You have any idea?

**Comment by eszlari** [comment]
You need to add `--enable-rpath` to ffmpeg's `config-opts`.

**Comment by Bleuzen** [comment]
Works, thank you!
