### ISSUE TITLE
Remove LAME

### ISSUE THREAD

**Issue by eszlari** [flathub/com.github.Bleuzen.FFaudioConverter#2]
LAME is included in the freedesktop 18.08 / KDE 5.12 runtime:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/desktop/lame.bst

**Comment by Bleuzen** [comment]
Removed in https://github.com/flathub/com.github.Bleuzen.FFaudioConverter/commit/2954374a897210447e61ed49a3a326e943a08f2e
thank you for the hint :D
